### ISSUE TITLE
[GUI] Shift some attributes from Client List to Client View

### ISSUE THREAD

**Issue by AaronCQL** [AY1920S2-CS2103T-F11-2/main#106]
Longer and non-essential attributes can be shifted to the Client View instead of residing in the Client List.

Proposed attributes to shift from Client List to Client View:

- Email
- Address
- Current weight
- Target weight
- Height
- Remark

**Comment by Yonggiee** [comment]
fixed in #104

**Comment by Yonggiee** [comment]
done
