### ISSUE TITLE
[GUI] Enhancements to Gender and Birthday attributes in Client List

### ISSUE THREAD

**Issue by AaronCQL** [AY1920S2-CS2103T-F11-2/main#107]
Instead of having separate rows for the `Gender` and `Birthday` attribute, perhaps we can consolidate and shift both of these to be beside their name. For example, `Bernice Yu (F, 20)`.

**Comment by Dban1** [comment]
If Birthday is not known, we will display age as "-"?

**Comment by Yonggiee** [comment]
> If Birthday is not known, we will display age as "-"?

same question for Gender

**Comment by AaronCQL** [comment]
How about a conditional check? So 4 cases:

1. No birthday, no gender
    - `Bernice Yu`
2. Birthday, no gender
    - `Bernice Yu (24)`
3. No birthday, gender
    - `Bernice Yu (F)`
4. Birthday, gender
    - `Bernice Yu (24, F)`

**Comment by Yonggiee** [comment]
can be done
