### ISSUE TITLE
[BUG] Add exercise error message is not consistent

### ISSUE THREAD

**Issue by AaronCQL** [AY1920S2-CS2103T-F11-2/main#113]
Steps to reproduce:

1. Enter `add-e n/push d/12-02-2020 reps/1 w/`

What is wrong:

- The error message of `Input Reps must be whole number (eg. 65)` is shown
- However, clearly the `reps` input is correct, but because we used a wrong prefix of `w/` instead of `ew/`, the parser will parse the whole `reps` as `1 w/` which will throw the error message

**Comment by Yonggiee** [comment]
To be added in FAQ in UG
