### ISSUE TITLE
[BUG] Schedule implementation consolidated bugs

### ISSUE THREAD

**Issue by AaronCQL** [AY1920S2-CS2103T-F11-2/main#129]
> Issues related to #108 

1.  Success message is not descriptive enough
    - `Training schedule has been added for MON Time: 12:59 - 13:00` does not say added for whom
2. `schedule 1` command
    - Seems like this clears the schedule of the first client, but the command output just says `Training schedule has been added for `
    - This is not consistent with our app, for example the `edit-c` command requires at least 1 keyword to be there. Allowing a user to just type `schedule 1` to clear all schedules is not very intuitive
3. Wrong example usage when entering wrong usage of command
    - Example shows: `schedule 1 d/mon st/1200 et/1400 d/fri st/1330 et/1500`
4. 0% test coverage for these files: `ScheduleCommand`, `ScheduleCommandParser`, all files in the `Schedule` model, `JsonAdaptedSchedule`. Please write some tests
5. Extra empty space after each end of schedule in the GUI (refer to screenshot)
    - <img width="199" alt="Screenshot_20200402_150204" src="https://user-images.githubusercontent.com/28671644/78219846-f3d5bc80-74f2-11ea-97a4-1289995a3021.png">
6. SO MANY PRINT STATEMENTS EVERYWHERE. Please clear them.
    - <img width="268" alt="Screenshot_20200402_151231" src="https://user-images.githubusercontent.com/28671644/78220570-61ceb380-74f4-11ea-8e17-11e0126700d1.png">
    - <img width="45" alt="Screenshot_20200402_151820" src="https://user-images.githubusercontent.com/28671644/78221033-326c7680-74f5-11ea-8119-3e60d53457c4.png">

**Comment by Dban1** [comment]
Done
1
3
5
6
