### ISSUE TITLE
[ENHANCEMENT] Schedule Inconsistent Error Message

### ISSUE THREAD

**Issue by Yonggiee** [AY1920S2-CS2103T-F11-2/main#148]
`Invalid command format! 
schedule: Adds the training schedule of the client, identified by the index number used in the displayed client list. The schedule should include the first 3 letters of the day, 
start and end time in 24 hour format, in 30 minutes denominations. Multiple training schedule can be added to a client.
Parameters: INDEX (a positive integer) d/DAY st/START_TIME et/END_TIME [MORE_SCHEDULE]...
Example: schedule 1 day/mon st/1200 et/1400 day/fri st/1330 et/1500`

`schedule 1 day/mon st/1200 et/1221` works fine and 30 minutes denominations not necessary

**Comment by Dban1** [comment]
Good catch, fixed.
