### ISSUE TITLE
[BUG] Calling graph on a non-existent exercise name throws uncaught exception

### ISSUE THREAD

**Issue by AaronCQL** [AY1920S2-CS2103T-F11-2/main#235]
Steps to reproduce:

1. View any client with `view-c`
2. Call graph with a non-existent exercise name like `graph n/asd a/reps sd/20-02-2020 ed/20-03-2020`
3. Following success message is shown:
    <img width="525" alt="Screenshot_20200408_100351" src="https://user-images.githubusercontent.com/28671644/78736646-40504a80-7980-11ea-9eda-d8bd2cbb77e9.png">
4. App throws uncaught `IndexOutOfBoundsException`

What is expected:

1. Success message to user should not be shown
2. Error should be thrown to user instead that says that the graph cannot be plotted because no exercises are found

**Comment by ziyingli** [comment]
Fixed but got another problem thats similar:
- when theres no reps/weight for that exercise, success message is shown
- App throws uncaught IndexOutOfBoundsException

**Comment by ziyingli** [comment]
No exercise within that date window
- but still shows success message
